<?php

namespace App\Enums;

enum ApplicationStatus: string
{
    case DISCOVERED = 'DISCOVERED';
    case MATCHED = 'MATCHED';
    case PENDING_REVIEW = 'PENDING_REVIEW';
    case READY_TO_APPLY = 'READY_TO_APPLY';
    case AUTO_APPLYING = 'AUTO_APPLYING';
    case APPLIED = 'APPLIED';
    case EXTERNAL_APPLICATION = 'EXTERNAL_APPLICATION';
    case COMPANY_WEBSITE = 'COMPANY_WEBSITE';
    case MANUAL_REQUIRED = 'MANUAL_REQUIRED';
    case FAILED = 'FAILED';
    case RETRYING = 'RETRYING';
    case ALREADY_APPLIED = 'ALREADY_APPLIED';
    case SKIPPED = 'SKIPPED';
    case INTERVIEW_REQUESTED = 'INTERVIEW_REQUESTED';
    case INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED';
    case REJECTED = 'REJECTED';
    case OFFER_RECEIVED = 'OFFER_RECEIVED';
}
